// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: couponresp.proto

package coupons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMIXText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Text    string     `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Reply   *TextReply `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *CMIXText) Reset() {
	*x = CMIXText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_couponresp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CMIXText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CMIXText) ProtoMessage() {}

func (x *CMIXText) ProtoReflect() protoreflect.Message {
	mi := &file_couponresp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CMIXText.ProtoReflect.Descriptor instead.
func (*CMIXText) Descriptor() ([]byte, []int) {
	return file_couponresp_proto_rawDescGZIP(), []int{0}
}

func (x *CMIXText) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CMIXText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CMIXText) GetReply() *TextReply {
	if x != nil {
		return x.Reply
	}
	return nil
}

type TextReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageId []byte `protobuf:"bytes,1,opt,name=messageId,proto3" json:"messageId,omitempty"`
	SenderId  []byte `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
}

func (x *TextReply) Reset() {
	*x = TextReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_couponresp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReply) ProtoMessage() {}

func (x *TextReply) ProtoReflect() protoreflect.Message {
	mi := &file_couponresp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReply.ProtoReflect.Descriptor instead.
func (*TextReply) Descriptor() ([]byte, []int) {
	return file_couponresp_proto_rawDescGZIP(), []int{1}
}

func (x *TextReply) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *TextReply) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

var File_couponresp_proto protoreflect.FileDescriptor

var file_couponresp_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x72, 0x65, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x22, 0x62, 0x0a, 0x08, 0x43,
	0x4d, 0x49, 0x58, 0x54, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x45, 0x0a, 0x09, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x69, 0x78, 0x78, 0x69, 0x72, 0x2f, 0x63, 0x6f, 0x75,
	0x70, 0x6f, 0x6e, 0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_couponresp_proto_rawDescOnce sync.Once
	file_couponresp_proto_rawDescData = file_couponresp_proto_rawDesc
)

func file_couponresp_proto_rawDescGZIP() []byte {
	file_couponresp_proto_rawDescOnce.Do(func() {
		file_couponresp_proto_rawDescData = protoimpl.X.CompressGZIP(file_couponresp_proto_rawDescData)
	})
	return file_couponresp_proto_rawDescData
}

var file_couponresp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_couponresp_proto_goTypes = []interface{}{
	(*CMIXText)(nil),  // 0: coupons.CMIXText
	(*TextReply)(nil), // 1: coupons.TextReply
}
var file_couponresp_proto_depIdxs = []int32{
	1, // 0: coupons.CMIXText.reply:type_name -> coupons.TextReply
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_couponresp_proto_init() }
func file_couponresp_proto_init() {
	if File_couponresp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_couponresp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CMIXText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_couponresp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_couponresp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_couponresp_proto_goTypes,
		DependencyIndexes: file_couponresp_proto_depIdxs,
		MessageInfos:      file_couponresp_proto_msgTypes,
	}.Build()
	File_couponresp_proto = out.File
	file_couponresp_proto_rawDesc = nil
	file_couponresp_proto_goTypes = nil
	file_couponresp_proto_depIdxs = nil
}
