// Code generated by protoc-gen-go. DO NOT EDIT.
// source: couponresp.proto

package coupons

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CMIXText struct {
	Text                 string              `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Reply                *TextReply          `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	Preview              *TextNetworkPreview `protobuf:"bytes,3,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CMIXText) Reset()         { *m = CMIXText{} }
func (m *CMIXText) String() string { return proto.CompactTextString(m) }
func (*CMIXText) ProtoMessage()    {}
func (*CMIXText) Descriptor() ([]byte, []int) {
	return fileDescriptor_0df6afd1dcee6c11, []int{0}
}

func (m *CMIXText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMIXText.Unmarshal(m, b)
}
func (m *CMIXText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMIXText.Marshal(b, m, deterministic)
}
func (m *CMIXText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMIXText.Merge(m, src)
}
func (m *CMIXText) XXX_Size() int {
	return xxx_messageInfo_CMIXText.Size(m)
}
func (m *CMIXText) XXX_DiscardUnknown() {
	xxx_messageInfo_CMIXText.DiscardUnknown(m)
}

var xxx_messageInfo_CMIXText proto.InternalMessageInfo

func (m *CMIXText) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CMIXText) GetReply() *TextReply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *CMIXText) GetPreview() *TextNetworkPreview {
	if m != nil {
		return m.Preview
	}
	return nil
}

type TextNetworkPreview struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextNetworkPreview) Reset()         { *m = TextNetworkPreview{} }
func (m *TextNetworkPreview) String() string { return proto.CompactTextString(m) }
func (*TextNetworkPreview) ProtoMessage()    {}
func (*TextNetworkPreview) Descriptor() ([]byte, []int) {
	return fileDescriptor_0df6afd1dcee6c11, []int{1}
}

func (m *TextNetworkPreview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextNetworkPreview.Unmarshal(m, b)
}
func (m *TextNetworkPreview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextNetworkPreview.Marshal(b, m, deterministic)
}
func (m *TextNetworkPreview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextNetworkPreview.Merge(m, src)
}
func (m *TextNetworkPreview) XXX_Size() int {
	return xxx_messageInfo_TextNetworkPreview.Size(m)
}
func (m *TextNetworkPreview) XXX_DiscardUnknown() {
	xxx_messageInfo_TextNetworkPreview.DiscardUnknown(m)
}

var xxx_messageInfo_TextNetworkPreview proto.InternalMessageInfo

func (m *TextNetworkPreview) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TextNetworkPreview) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TextNetworkPreview) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type TextReply struct {
	Message              string              `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SenderId             []byte              `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	UniqueId             []byte              `protobuf:"bytes,3,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	Preview              *TextNetworkPreview `protobuf:"bytes,4,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TextReply) Reset()         { *m = TextReply{} }
func (m *TextReply) String() string { return proto.CompactTextString(m) }
func (*TextReply) ProtoMessage()    {}
func (*TextReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0df6afd1dcee6c11, []int{2}
}

func (m *TextReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextReply.Unmarshal(m, b)
}
func (m *TextReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextReply.Marshal(b, m, deterministic)
}
func (m *TextReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextReply.Merge(m, src)
}
func (m *TextReply) XXX_Size() int {
	return xxx_messageInfo_TextReply.Size(m)
}
func (m *TextReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TextReply.DiscardUnknown(m)
}

var xxx_messageInfo_TextReply proto.InternalMessageInfo

func (m *TextReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TextReply) GetSenderId() []byte {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *TextReply) GetUniqueId() []byte {
	if m != nil {
		return m.UniqueId
	}
	return nil
}

func (m *TextReply) GetPreview() *TextNetworkPreview {
	if m != nil {
		return m.Preview
	}
	return nil
}

func init() {
	proto.RegisterType((*CMIXText)(nil), "coupons.CMIXText")
	proto.RegisterType((*TextNetworkPreview)(nil), "coupons.TextNetworkPreview")
	proto.RegisterType((*TextReply)(nil), "coupons.TextReply")
}

func init() {
	proto.RegisterFile("couponresp.proto", fileDescriptor_0df6afd1dcee6c11)
}

var fileDescriptor_0df6afd1dcee6c11 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0xe5, 0xfe, 0x21, 0xcd, 0xd1, 0xa1, 0x3a, 0x31, 0x44, 0xb0, 0x54, 0x99, 0x32, 0x65,
	0x00, 0xf1, 0x02, 0x30, 0x65, 0x00, 0x55, 0x27, 0x06, 0x56, 0x20, 0x27, 0x64, 0x91, 0xc6, 0xc6,
	0x7f, 0x68, 0x99, 0x78, 0x09, 0x1e, 0x18, 0xd9, 0x4e, 0x23, 0x10, 0x4b, 0xb7, 0xfb, 0xee, 0x7e,
	0xf7, 0xf9, 0x3b, 0xc3, 0xea, 0x45, 0x79, 0xad, 0x7a, 0xc3, 0x56, 0xd7, 0xda, 0x28, 0xa7, 0x30,
	0x4b, 0x1d, 0x5b, 0x7e, 0xc1, 0xe2, 0xf6, 0xae, 0x79, 0x7c, 0xe0, 0xbd, 0x43, 0x84, 0x99, 0xe3,
	0xbd, 0x2b, 0xc4, 0x5a, 0x54, 0x39, 0xc5, 0x1a, 0x2b, 0x98, 0x1b, 0xd6, 0xdd, 0x67, 0x31, 0x59,
	0x8b, 0xea, 0xf4, 0x12, 0xeb, 0x61, 0xb1, 0x0e, 0x1b, 0x14, 0x26, 0x94, 0x00, 0xbc, 0x86, 0x4c,
	0x1b, 0xfe, 0x90, 0xbc, 0x2b, 0xa6, 0x91, 0xbd, 0xf8, 0xc3, 0xde, 0xb3, 0xdb, 0x29, 0xf3, 0xb6,
	0x49, 0x08, 0x1d, 0xd8, 0x92, 0x00, 0xff, 0x8f, 0x71, 0x05, 0x53, 0x6f, 0xba, 0x21, 0x49, 0x28,
	0xf1, 0x0c, 0xe6, 0x4e, 0xba, 0x8e, 0x63, 0x90, 0x9c, 0x92, 0x08, 0x5d, 0xb9, 0x7d, 0x7a, 0xe5,
	0xf8, 0xe4, 0x92, 0x92, 0x28, 0xbf, 0x05, 0xe4, 0x63, 0x3e, 0x2c, 0x20, 0xdb, 0xb2, 0xb5, 0x81,
	0x4a, 0x7e, 0x07, 0x89, 0xe7, 0xb0, 0xb0, 0xdc, 0xb7, 0x6c, 0x9a, 0x36, 0xda, 0x2e, 0x69, 0xd4,
	0x61, 0xe6, 0x7b, 0xf9, 0xee, 0xb9, 0x69, 0x07, 0xf3, 0x51, 0xff, 0x3e, 0x75, 0x76, 0xfc, 0xa9,
	0x37, 0x93, 0x8d, 0x78, 0x3e, 0x89, 0xff, 0x7f, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xac,
	0x09, 0x0f, 0x93, 0x01, 0x00, 0x00,
}
